spring.application.name=kino
spring.datasource.url=jdbc:postgresql://localhost:5432/kino_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
app.jwt.secret=${JWT_SECRET}